repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: strip-image-metadata
        name: Strip image metadata
        language: system
        entry: scripts/strip-image-metadata.sh
        files: \.(jpg|jpeg|png|tiff|tif)$
