repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: strip-image-metadata
        name: Strip image metadata
        language: system
        entry: scripts/strip-image-metadata.sh
        files: \.(jpg|jpeg|png|tiff|tif)$
      - id: prettier
        name: Prettier
        language: system
        entry: bunx prettier --write --ignore-unknown
        types: [text]
      - id: astro-check
        name: Astro Check
        language: system
        entry: bunx astro check
        pass_filenames: false
        types: [text]
      - id: astro-build
        name: Astro Build
        language: system
        entry: bunx astro build
        pass_filenames: false
        types: [text]
